version: '3.8'

networks:
  notes-network:
    driver: bridge

volumes:
  # postgres-volume:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: ${PWD}/postgresql
  #     o: bind
  pgadmin-volume:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/pgadmin
      o: bind
  redis-volume:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/redis
      o: bind

services:
  postgres-service:
    image: postgres:alpine
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - notes-network

  pgadmin-service:
    image: dpage/pgadmin4
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - pgadmin-volume:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    networks:
      - notes-network
    depends_on:
      - postgres-service

  redis-service:
    image: redis:alpine
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf 
      - redis-volume:/data